FROM node:18-bullseye

WORKDIR /app

COPY ./package.json ./

RUN yarn install --production
RUN yarn add pg

COPY . .

ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_USERNAME $DATABASE_USERNAME
ENV DATABASE_PASSWORD $DATABASE_PASSWORD


ENV NODE_ENV production
ENV DB_CLIENT='postgres'

EXPOSE 1337

CMD ["npm", "start"]

